### ISSUE TITLE
Ruby Capstone project setup

### ISSUE THREAD

**Issue by RoyJumah** [RoyJumah/catalog-of-my-things#27]
> In this issue, we have listed the participants and tasks assigned to each group member
- There are three of us in the group 
@RoyJumah - Will handle tasks for `Team member #1`
@Hassaanjbaig-code  - Will handle tasks for `Team member #2`
@kennedyowusu - Will handle tasks for `Team member #3`

- This is the link to the project that we set up [link](https://github.com/RoyJumah/catalog-of-my-things/projects/1)

**Comment by TedLivist** [comment]
## STATUS: APPROVED ✔️ ✔️

Hi @RoyJumah, @kennedyowusu and @Hassaanjbaig-code,

✔️ Tasks are properly assigned

Your project is complete!  There is nothing else to say other than... it's time to go ahead with the project :shipit: 
Congratulations! 🎉

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the Issue thread if something is not 100% clear. And please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
